import manifest from "@/content/blog.json";

export type BlogLocale = "en" | "pt";

export type BlogAuthor = {
  id: string;
  name: string;
  linkedin: string;
  photo: string;
  headline?: string;
  headlinePt?: string;
};

export type BlogPostSummary = {
  slug: string;
  title: string;
  description: string;
  date: string;
  coverImage: string | null;
  tags: string[];
  locale: BlogLocale;
  author: BlogAuthor;
};

export type BlogPost = BlogPostSummary & { html: string };

type Manifest = { generatedAt: string; posts: Record<BlogLocale, BlogPost[]> };

// Generated by scripts/build-blog.mjs before every build; posts in both locales, PT already merged over EN.
const data = manifest as unknown as Manifest;

/** Site locales are en/pt/es; the blog is written in en and pt, es reads en. */
export function toBlogLocale(lang: string): BlogLocale {
  return lang === "pt" ? "pt" : "en";
}

export function getBlogPosts(locale: BlogLocale): BlogPostSummary[] {
  return data.posts[locale].map(({ html: _html, ...summary }) => summary);
}

export function getAllBlogSlugs(): string[] {
  return Array.from(new Set([...data.posts.en, ...data.posts.pt].map((p) => p.slug)));
}

export function getBlogPostBySlug(slug: string, locale: BlogLocale): BlogPost | null {
  return data.posts[locale].find((p) => p.slug === slug) ?? data.posts.en.find((p) => p.slug === slug) ?? null;
}
